name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deploy target
        required: false
        default: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package app
        # This zips everything in the root so run.py is at the top level
        #run: zip -r release.zip . -x "*.git*" -x "*venv*" -x "*__pycache__*" -x "*.env" -x "*instance*"
        run: |
          pwd
          ls -la
          zip -r release.zip * \
            -x "*.git*" \
            -x "*venv*" \
            -x "*__pycache__*" \
            -x "*.env" \
            -x "*instance*"

      - name: Verify package contents
        run: unzip -l release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smart-retail-niha'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip