name: CD
#
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deploy target
        required: false
        default: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        # We zip the contents so run.py is at the root of the zip
        run: zip -r release.zip . -x '*.git*' -x '*venv*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'smart-retail-niha' # Replace with your actual app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip

          #